export const STRINGS = {
  loading: 'Loading...',
  error: 'Error: ',
  searchPlaceholder: 'Search cryptocurrency...',
  sortByPriceAsc: 'Sort by Price (Asc)',
  sortByPriceDesc: 'Sort by Price (Desc)',
  sortByNameAsc: 'Sort by Name (A-Z)',
  sortByNameDesc: 'Sort by Name (Z-A)',
  sortBy: 'Sort by',
  convert: 'Convert',
  converting: 'Converting...',
  conversionResult: 'Conversion Result',
  selectCrypto: 'Select a cryptocurrency',
  amount: 'Amount',
  from: 'From:',
  to: 'To:',
  noData: 'No data available.',
  back: 'Back',
  price: '💰 Price: ',
  percentChange: '📈 24h Change: ',
  marketCap: '🏛 Market Cap: ',
  volume24h: '📊 24h Volume: ',
  supply: '🔗 Supply: ',
};
